### ISSUE TITLE
Set up the rust folder

### ISSUE THREAD

**Issue by alexandruradovici** [UPB-CS-OpenSourceUpstream/tockloader#2]
Setup the rust folder for the new tockloader. This implies using cargo for a default rust project structure.

**Comment by eva-cosma** [comment]
Hello! What should we do with the python version when porting to rust? Do we leave it as-is in the repository, or should we separate the rust and python versions into two different folders, keeping at the root of the repository only the project-specific files (README, LICENSE, etc.)

**Comment by alexandruradovici** [comment]
I suggest separating them into different folders.

**Comment by alexandruradovici** [comment]
Closed by #8.
